name: widgeto
description: Convert your widget to <dynamic>.
version: 0.0.1
homepage: https://github.com/OdilonDamasceno/widgeto

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  pdf: ^3.3.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
